import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
    <p>
      The title is: {{ title }}
    </p>
    <input [value]="generateTile()">
    <button>Save</button>
  `,
  styleUrls: ['./input-button-unit.component.scss']
})
export class InputButtonUnitComponent implements OnInit {
  title = 'Hello World';

  constructor() {
  }

  ngOnInit() {
    setTimeout(() => {
      this.title = 'This is not the title you are looking for...';
    }, 3000);
  }

  generateTile(): string {
    return 'This title was generated by a method';
  }

}
